<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-13 14:55:47
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-20 09:47:26
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
    <el-button 
        class="cv-widget cv-button" 
        :id="`cv-button_${id}`" 
        :style="style"
        :type="btnType"
        :plain="plain"
        :size="size"
        :round="round"
        :circle="circle"
        :icon="icon"
        @click="onClick">
        {{ btnText }}
    </el-button>
</template>

<script>
import mixin from './mixin'
export default {
    name:'CvButton',
    mixins:[mixin],
    data(){
        return {
            btnType:'primary',
            btnText:'确定',
            plain:false,
            size:'medium',
            icon:'',
            round:false,
            circle:false
        }
    },
    methods:{
        onClick(){
            this.$cvr.emit(this.id + '_click') 
        }
    },
    created(){
        this.style = {...this.cfg.style}
        const attrs = this.cfg.attr
        if(attrs){            
            this.btnType = attrs.type || "primary"
            this.btnText = attrs.text
            this.round = attrs.round || false
            this.circle = attrs.circle || false
            this.plain = attrs.plain || false
            this.size = attrs.size || 'medium'
            this.icon = attrs.icon || ''
        }
    }
}
</script>