<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-13 14:55:47
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-19 11:01:42
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
    <el-date-picker class="cv-widget cv-datepicker" :id="`cv-datepicker_${id}`" 
        v-model="value"
        :type="type"
        :placeholder="placeholder"
        :style="style"
        :format="format"
        :value-format="format"
        @change="changeV">
    </el-date-picker>
</template>

<script>
import { dateTimeHelper } from '../helper'
import mixin from './mixin'
export default {
    name:'CvDatepicker',
    mixins:[mixin],
    data(){
        return {
            value:'',
            format:'yyyy-MM-dd',
            placeholder:''
        }
    },
    created(){        
        this.placeholder = this.cfg.placeholder
        this.format = this.cfg.format || 'yyyy-MM-dd'
        if(this.cfg.value){
            const valueMatched = this.cfg.value.match(/\${(\w+)}$/)
            if(valueMatched && valueMatched.length === 2 && valueMatched[1]){
                this.value = dateTimeHelper.getVariable(valueMatched[1],this.format) || ''
            }else{
                this.value = this.cfg.value
            }
        }
        
    }
}
</script>