<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-13 14:55:41
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-21 11:23:53
 * @Tool: Auto Generated by koroFileHeader
-->

<script type="text/jsx">
    //    id:'012',
    //     type:'dynamicLabel',
    //     content:'风电运维情况，时间-${0},区域-${1}',
    //     style:{
    //         fontSize:'18px',
    //         color:'#ff00ff',
    //         fontWeight:'600',
    //         left:'200px',
    //         top:'40px'
    //     },
    //     slots:[{
    //         from:'011',
    //         get:'value',
    //         style:{
    //             fontSize:'30px',
    //             color:'blue'
    //         }
    //     },{
    //         from:'013',
    //         get:'text',
    //         style:{
    //             color:'purple'
    //         }
    //     }]
import mixin from './mixin'
export default {
    name:'CvDynamicLabel',
    mixins:[mixin],
    data(){
        return{
            content:[],
            slots:[], // 配置信息中的插槽配置
            slotsValues:[] // 插槽值
        }
    },
    created(){
       const parsedContent = this.cfg.content.replace(/\${(\d+)}/g, '#&#$!$1$!#&#')
        this.content = parsedContent.split('#&#')
        //slot 内容占位形式为"$!0$!"
        this.bindSlots()
    },
    render(){
        return (
            <span class="cv-widget cv-dynamic-label" id={ `cv-dynamic-label_${this.id}` } style={ this.style || {} }>
              {
                  this.content.map(c=>{
                      if(/^\$!\d+\$!$/.test(c)){
                          const idx = ~~(c.replace(/\$!/g,''))
                          const slot = this.slots[idx]
                          return <span style={ slot.style || {} }>{ this.slotsValues[idx] }</span>
                      }else{                          
                          return <span>{c}</span>
                      }
                  })
              }
            </span>
        )
    },
    methods:{
        updateSlots(idx,getField){
            return (event)=>{
                this.$set(this.slotsValues,idx,event[getField])
            }    
        },
        bindSlots(){
            const slots =this.cloneDeep(this.cfg.slots)
            this.slots = slots
            if(slots && slots.length>0){
                this.slotValues = Array(slots.length).fill('')                
                this.$cvr.bindSlots(this)
            }
        }
    }
}
</script>

<style>

</style>