<!--
 * @Description: html片段,可包含插值文本
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-21 09:37:31
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-21 16:36:13
 * @Tool: Auto Generated by koroFileHeader
-->
<script type="text/jsx">
import mixin from './mixin'
export default {
    name:'CvHtmlFragment',
    mixins:[mixin],
    data(){
        return{
            parsedContent:'',
            slots:[], // 配置信息中的插槽配置
            slotsValues:[] // 插槽值
        }
    },
    watch:{
        slotsValues:{
            handler(newer){
                let parsingContent = this.cfg.content
                let regex
                newer.forEach((v,idx) => {
                    regex = new RegExp('\\$\\{'+ idx  + '\\}',"gm")
                    parsingContent = parsingContent.replace(regex,v)
                })
                this.parsedContent = parsingContent
            },
            deep:true
        }
    },
    created(){
        const rawContent = this.cfg.content
        this.parsedContent = rawContent
        if(rawContent.match(/\${\d+}/g)){            
            this.slots = this.cloneDeep(this.cfg.slots)
            this.bindSlots(this.slots)
        }
    },
    render(){
        return (
            <p class="cv-widget cv-html-fragment" id={ `cv-html-fragment_${this.id }` } domPropsInnerHTML={ this.parsedContent } style={ this.style || {} }></p>
        )
    },
    methods:{
        updateSlots(idx,getField){
            return (event)=>{
                this.$set(this.slotsValues,idx,event[getField])
            }
        },
        bindSlots(slots){
            if(slots && slots.length>0){                
                this.slotValues = Array(slots.length).fill('')
                this.$cvr.bindSlots(this)
            }
        }
    }
}
</script>