<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-13 14:55:47
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-20 09:10:12
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
    <el-select class="cv-widget cv-select" :id="`cv-select_${id}`" v-model="value" :placeholder="placeholder" :style="style"  @change="changeV">
        <el-option
        v-for="item in options"
        :key="item.value"
        :label="item.label"
        :value="item.value">
        </el-option>
    </el-select>
</template>

<script>
import { cloneDeep } from 'lodash'
import { loadKeyValueArrayData } from '../api/dataLoader'
import mixin from './mixin'
export default {
    name:'CvSelect',
    mixins:[mixin],
    data(){
        return {
            value:'',
            placeholder:'',
            dataSource:null,
            options:null
        }
    },
    methods:{
        changeV(v){
            this.$cvr.emit(this.id + '_change', { value:v, text: this.getText() })            
        },
        onCompReady(){            
            console.log(`widget - ${this.id} ready`)
            this.$cvr.emit(this.id + '_init',{ value: this.value, text:this.getText()  }) 
        },
        getText(){
            const selObj = this.options.find(c=>c.value === this.value)
            let text = ''
            if(selObj){
                text = selObj.label
            }
            return text
        }
    },
    created(){
        this.value = this.cfg.value
        this.placeholder = this.cfg.placeholder
        this.dataSource = cloneDeep(this.cfg.dataSource)
        if(Array.isArray(this.dataSource.data)){
            this.options = cloneDeep(this.dataSource.data)
        }else{
            this.options = loadKeyValueArrayData(this.dataSource)
        }
    }
}
</script>