/*
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-12-04 15:06:33
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-12-04 15:26:24
 * @Tool: Auto Generated by koroFileHeader
 */
export function getPageList(){
    const designPages = window.localStorage.getItem('designPages')
    let pages = []
    if(designPages){
        pages = JSON.parse(designPages)
                        
    }
    return pages.map(c=>{
        return { id:c.id,title:c.title,creator:c.creator}
    })
}

export function getPageCfg(idPage){
    const designPages = window.localStorage.getItem('designPages')
    if(designPages){
        const pages = JSON.parse(designPages)
        if(Array.isArray(pages)){
            const idx = pages.findIndex(c=>c.id === idPage)
            if(idx>=0){
                return {...pages[idx]}
            } 
        }
    }
    return null
}

export function addNewPageCfg(page){
    const designPages = window.localStorage.getItem('designPages')
    let pages = []
    if(designPages){
        pages = JSON.parse(designPages)                               
    }
    pages.push(page)
    // todo: 从设计页面保存
    window.localStorage.setItem('designPages',JSON.stringify(pages))
}

export function savePageCfg(page){
    const designPages = window.localStorage.getItem('designPages')
    if(designPages){
        const pages = JSON.parse(designPages)
        if(Array.isArray(pages)){
            const idx = pages.findIndex(c=>c.id === page.id)
            if(idx>=0){
                pages[idx] = page
                window.localStorage.setItem('designPages', JSON.stringify(pages))
            } 
        }
    }
}

export function updatePageTitle(page){
    const designPages = window.localStorage.getItem('designPages')
    if(designPages){
        const pages = JSON.parse(designPages)
        if(Array.isArray(pages)){
            const idx = pages.findIndex(c=>c.id === page.id)
            if(idx>=0){
                pages[idx].title = page.title
                window.localStorage.setItem('designPages',JSON.stringify(pages))
            }
        }                   
    }
}
