<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-09 17:58:09
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-12-06 21:24:08
 * @Tool: Auto Generated by koroFileHeader
-->

<template>
  <div class="designer-board">
    <div id="designer-board-editor" @dragover="dragover" @dragstart="dragstart" @drop="drop">
        <div style="width:200px;height:200px;background-color:red"></div>
    </div>
    <de-html-fragment v-for="ht in htmlViews" :key="ht.id" :id="ht.id" :content="ht.content" :isNewNode="ht.isNewNode" :type="ht.type" :outStyle="ht.style" @updateEditorBackground="updateEditorBackground" @edit="editHtml" @stopedit="stopEditHtml"></de-html-fragment>
    <div style="display:none;" id="designer-tinymce-editor"></div>
  </div>
</template>

<script>
import Editor from './editor'
import DeHtmlFragment from './dom/htmlFragment'
import Tinymce from 'tinymce/tinymce'
import 'tinymce/themes/silver/theme'
import 'tinymce/icons/default'
import 'tinymce/plugins/link'
import 'tinymce/plugins/lists'
import 'tinymce/plugins/paste'
import 'tinymce/plugins/autolink'
import 'tinymce/plugins/save'

export default {
    name:'DesignerBoard',
    components:{
        DeHtmlFragment
    },
    props:{
        cfg:{
            type:Object,
            required:true
        }
    },
    data(){
        return{
            editor:null,
            htmlViews:[], // {content:'',style:{}} 
            editingHtmlFragment:null,
            tinymceEditor:null
        }
    },
    watch:{
        '$props.cfg':{
            handler(newer){
                this.loadFromCfg(newer)
            }
        }
    },
    methods:{           
        loadFromCfg(cfg){
            //设置画布样式
            // this.editor
            // 加载widgets
            cfg.widgets.forEach(w => {
                this.htmlViews.push(w)
            })
        },
        dragstart(e){
            e.preventDefault()
        },
        dragover(e){
            e.preventDefault()
        },
        drop(e){
            var text= e.dataTransfer.getData("addShape");
            var x=parseInt(e.offsetX)+0.5
            var y=parseInt(e.offsetY)+0.5
            try{
                var data=JSON.parse(text)
                data['x']=x;
                data['y']=y;
                this.editor.addShape(data)
            }catch(err){
            //window.console.log(err);
            }
        },
        addWidget(hv){
            /*eslint no-debugger: "off"*/
            hv.isNewNode = true
            this.htmlViews.push(hv)
        },
        editHtml(e){
            if(this.editingHtmlFragment){
                this.$message.error('有其他未完成的编辑操作!')
                return
            }
            this.editingHtmlFragment = {...e}
            if(this.tinymceEditor){
                this.tinymceEditor.show()
                this.tinymceEditor.setContent(e.content)
                this.setTinyMceBackground(e.backgroundColor)
            }
        },
        updateEditorBackground(e){
            if( !this.editingHtmlFragment || e.id !== this.editingHtmlFragment.id){
                return
            }
            this.setTinyMceBackground(e.backgroundColor)
        },
        setTinyMceBackground(backgroundColor){
            document.querySelector('.designer-board #designer-tinymce-editor_ifr').style.backgroundColor = backgroundColor
        },
        stopEditHtml(){
            this.editingHtmlFragment = null
            if(this.tinymceEditor){
                this.tinymceEditor.hide()
            }
        },
        initTinyMCEEditor(){
            let self = this
            Tinymce.init({
            // selector: '#${this.id}',
                selector: '#designer-tinymce-editor',
                // language_url: './langs/zh_CN.js',
                // language: 'zh_CN',
                height:400,
                save_enablewhendirty:false,
                skin_url: '/static/tinymce/skins/ui/oxide',
                content_css: '/static/tinymce/skins/content/default/content.css',
                menubar: false,
                // inline: true,
                // plugins:'advlist lists pagebreak preview print code',
                // toolbar:'undo redo| bold italic underline strikethrough | formatselect | alignleft aligncenter alignright alignjustify | outdent indent | numlist bullist | forecolor backcolor removeformat | code',
                plugins: [
                    'link',
                    'lists',
                    'paste',
                    'autolink',
                    'save'
                ],
                toolbar: [
                    'undo redo | bold italic underline | fontselect fontsizeselect',
                    'forecolor backcolor | alignleft aligncenter alignright alignfull | numlist bullist outdent indent | | save'
                ],
                // menubar: false,
                branding: false, // 去水印
                browser_spellcheck: true, // 拼写检查
                elementpath: false, // 禁用编辑器底部的状态栏
                statusbar: false, // 隐藏编辑器底部的状态栏
                paste_data_images: false, // 允许粘贴图像
                // autosave_interval: '60s', // 自动保存的时间间隔
                save_onsavecallback: function (editor){ 
                    self.$cvd.emit('changeWidget',{id:self.editingHtmlFragment.id, content: editor.getContent()})
                    editor.hide()
                    self.editingHtmlFragment = null
                }
        }).then(editors => {
            console.log('tinymce editors ready', editors)
            this.tinymceEditor = editors[0]  
            })
        }
    },
    mounted(){
        //初始化编辑器，第二个参数是画布属性
        this.editor = new Editor('#designer-board-editor',{...this.$props.cfg.style})
        this.$cvd.on('addWidget',this.addWidget)
        this.loadFromCfg(this.$props.cfg)
        this.initTinyMCEEditor()
    },
    beforeDestroy(){
        this.editor = null
        this.$cvd.off('addWidget',this.addWidget)
        this.tinymceEditor.destroy()
    }
}
</script>

<style lang="scss"  scoped>
.designer-board{
  position: relative;
  flex:1;
  height: 100%;
  overflow: auto;
  .board-top-bar{
      height: 30px;
      padding: 10px;
      border: 1px solid #cccccc;
      font-size: 12px;
      .el-input-number.el-input-number--mini.is-without-controls {
          width: 40px;
          height: 22px;
          line-height: 22px;
          margin: 0 4px;
        /deep/.el-input__inner {
            padding-left: 2px;
            padding-right: 2px;
            height: 22px;
           line-height: 22px;
        }
      }
  }
  #designer-board-editor{
      background: #f4f4f4;
      text-align: left;
      box-sizing: border-box;
    //   height: 800px;
    //   margin:0 auto;
    //   position: relative;
    //   top:50%;
    //   transform: translateY(-50%);
    // display: flex;
    // align-items: center;
    // justify-content: center;
    // border: 1px solid #cccccc;
  }  
   /deep/ .tox-tinymce{
        width: 600px;
        height: 600px;
        position: absolute;
        top:calc(50% - 200px);
        left:calc(50% - 300px);
    }
}
</style>