<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-09 17:58:09
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-23 17:39:43
 * @Tool: Auto Generated by koroFileHeader
-->

<template>
  <div class="designer-board">
    <div id="designer-board-editor" @dragover="dragover" @dragstart="dragstart" @drop="drop">
    </div>
    <div></div>
    <de-html-view v-for="ht in htmlViews" :key="ht.id" :content="ht.content" :style="ht.style"></de-html-view>
  </div>
</template>

<script>
import Editor from './editor'
import DeHtmlView from './dom/htmlView'
export default {
    name:'DesignerBoard',
    components:{
        DeHtmlView
    },
    data(){
        return{
            editor:null,
            htmlViews:[] // {content:'',style:{}} 
        }
    },
    methods:{              
        dragstart(e){
            e.preventDefault()
        },
        dragover(e){
            e.preventDefault()
        },
        drop(e){
            var text= e.dataTransfer.getData("addShape");
            var x=parseInt(e.offsetX)+0.5;
            var y=parseInt(e.offsetY)+0.5;
            try{
                var data=JSON.parse(text);
                data['x']=x;
                data['y']=y;
                this.editor.addShape(data)    
            }catch(err){
            //window.console.log(err);
            }
        },
        addWidget(widget){
            const shape = widget.cfg.dataShape
            const parsedWidget = {id:widget.id, content:widget.cfg.dataShape.path, style:{top:shape.y+'px',left:shape.x+'px',padding:'20px',border:'1px solid red'}}
            this.htmlViews.push(parsedWidget)
        }
    },
    mounted(){
        this.$cvd.on('addWidget',this.addWidget)
        this.editor = new Editor('#designer-board-editor')
    }
}
</script>

<style lang="scss"  scoped>
.designer-board{
  position: relative;
  flex:1;
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  .board-top-bar{
      height: 30px;
      padding: 10px;
      border: 1px solid #cccccc;
      font-size: 12px;
      .el-input-number.el-input-number--mini.is-without-controls {
          width: 40px;
          height: 22px;
          line-height: 22px;
          margin: 0 4px;
        /deep/.el-input__inner {
            padding-left: 2px;
            padding-right: 2px;
            height: 22px;
           line-height: 22px;
        }
      }
  }
  #designer-board-editor{
      background: #f4f4f4;
      text-align: left;
      box-sizing: border-box;
      flex:1;
      overflow: auto;
    //   height: 800px;
    //   margin:0 auto;
    //   position: relative;
    //   top:50%;
    //   transform: translateY(-50%);
    // display: flex;
    // align-items: center;
    // justify-content: center;
    // border: 1px solid #cccccc;
  }
}
</style>