/*
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-12-02 10:00:58
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-12-02 10:03:09
 * @Tool: Auto Generated by koroFileHeader
 */
export function uuid() {
    function S4() {
        return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1)
    }
    function guid() {
        return S4() + S4() + S4() + S4()
    }
    return guid();
}