/*
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-11 17:11:59
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-23 17:14:30
 * @Tool: Auto Generated by koroFileHeader
 */

class Command {
    constructor(name,editor) {
        this.name = name;
        this.editor = editor
    }
    execute() { }
    undo() { }
    redo() {
        this.execute();
    }
}

// 增加新的图形
class AddNodes extends Command {
    constructor(nodes, editor) {
        super('addShape',editor)
        this.nodes = nodes
    }
    execute() {
        this.nodes.forEach(item => {
            this.editor.addNode(item)
        })
    }
    undo() {
        this.nodes.forEach(item => {
            this.editor.removeNode(item)
        })
    }
}

// 增加新的dom部件
class AddWidgets extends Command {
    constructor(widgets, editor) {
        super('addDomWidget',editor)
        this.widgets = widgets
    }
    execute() {
        this.widgets.forEach(item => {
            this.editor.addWidget(item)
        })
    }
    undo() {
        this.nodes.forEach(item => {
            this.editor.removeWidget(item)
        })
    }
}

export {
    AddNodes,
    AddWidgets
}