/*
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-25 09:32:49
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-25 09:35:31
 * @Tool: Auto Generated by koroFileHeader
 */
import Vue from 'vue'
import Vuex from 'vuex'
import designer from './modules/designer'

Vue.use(Vuex)
const store = new Vuex.Store({
  modules: {
    designer
  }
})

export default store
