/*
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-16 16:58:03
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-19 17:42:11
 * @Tool: Auto Generated by koroFileHeader
 */
import BaseChart from './_baseChart'
import barSchema from '../schema/bar'
import {loadLineBarData} from '../../api/dataLoader'

class ChartBar extends BaseChart{
    constructor(dom, cfg){
        super(dom, barSchema, cfg) 
    }
    /**
     * @description: 根据数据源配置及传入参数param获取数据
     * @param {*} params:[{prop:'time',valueFrom:''}]    
     * @return {*}
     */
    loadData(params){        
        const data = loadLineBarData(this.merge({},this.dataSource,params))
        this.fillData(data)
        console.log('-----bar draw')
    }
    fillData(data){        
        const { xAxisData, seriesData } = data
        let series=[]
        series.push({
            type:'bar',
            data:seriesData
        })
        this.setOption({series})
        if(xAxisData){
            this.setOption({xAxis:{data:xAxisData}})
        }
        this.draw()
    }
    onEventTrigger(params,events){
        console.log('onEventTrigger', params,events)
    }
}


export default ChartBar