/*
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-20 10:13:06
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-20 11:16:52
 * @Tool: Auto Generated by koroFileHeader
 */
import BaseChart from './_baseChart'
import pieSchema from '../schema/pie'
import { loadPieData } from '../../api/dataLoader'

class ChartPie extends BaseChart{
    constructor(dom, cfg){
        super(dom, pieSchema[cfg.type], cfg) 
    }
        /**
     * @description: 根据数据源配置及传入参数param获取数据
     * @param {*} params:[{prop:'time',valueFrom:''}]    
     * @return {*}
     */
    loadData(params){
        const data = loadPieData(this.merge({},this.dataSource,params))
        this.fillData(data)
    }
    fillData(data){
        let series=[]
        series.push({
            type:'pie',
            data
        })
        this.setOption({series})
        this.draw()
    }
    onEventTrigger(params,events){
        console.log('onEventTrigger', params,events)
    }
}


export default ChartPie