/*
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-18 14:25:25
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-19 09:22:04
 * @Tool: Auto Generated by koroFileHeader
 */
import moment from 'moment'
export const dateTimeHelper = {
    getCurrentDate(format){
        if(!format){
            format = "YYYY-MM-DD"
        }else{
            format = format.replace('yyyy-','YYYY-').replace('-dd','-DD')
        }
        return moment().format(format)
    },
    getDateRange(range) {
        let start, end
        if (range === 'week') {
            start = moment().week(moment().week() - 1).startOf('week').add(1, 'd').format('YYYY-MM-DD HH:mm:ss')
            end = moment().week(moment().week() - 1).endOf('week').add(1, 'd').format('YYYY-MM-DD HH:mm:ss')
        } else if (range === 'month') {
            start = moment().month(moment().month() - 1).startOf('month').format('YYYY-MM-DD HH:mm:ss')
            end = moment().month(moment().month() - 1).endOf('month').format('YYYY-MM-DD HH:mm:ss')
        } else if (range === 'quarter') {
            start = moment().quarter(moment().quarter() - 1).startOf('quarter').format('YYYY-MM-DD HH:mm:ss')
            end = moment().quarter(moment().quarter() - 1).endOf('quarter').format('YYYY-MM-DD HH:mm:ss')
        }
        return [start, end]
    },
    getVariable(variable,format){
        let v = null
        switch(variable){
            case 'dateNow':
                v = this.getCurrentDate(format)
                break;
            default:
                break
        }
        return v
    }
}