<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-13 09:24:23
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-19 15:10:23
 * @Tool: Auto Generated by koroFileHeader
-->
<script type="text/jsx">
import { cloneDeep, merge } from 'lodash'
import CvInput from './widgets/input'
import CvSelect from './widgets/select'
import CvDatepicker from './widgets/datePicker'
import CvDynamicLabel from './widgets/dynamicLabel'
import CvFreeTable from './widgets/freeTable'
import chartHelper from './chart'

export default {
    name:'CustomView',
    props:{
        schema:{
            type:Object,
            default:()=> {return { title:'空页' }}
        }
    },
    components:{
        CvInput,
        CvSelect,
        CvDatepicker,
        CvDynamicLabel,
        CvFreeTable
    },
    data(){
        return {
            pageStyle:{
                background:'#ffffff',
                width:'100%',
                height:'100%'
            },
            widgets:[], // 页面部件
            charts:[], // 图表组件
            prefixIdChart:'cv-chart_'
        }
    },
    methods:{
        onChartClick(chart){
            this.$emit('chartclicked',chart)
        },
        renderCharts(){
            this.charts.forEach(c => {
                let chart =  chartHelper.create(c.type,`#${chartHelper.prefixId}${c.id}`,c)
                // todo getData
                if(chart){
                    if(!chart.dataSource.lazyLoad){                        
                        chart.loadData()
                    }
                    this.$cvr.addComp(c.id, chart)
                    console.log(`chart - ${c.id} - created`)
                }                
            })
        }
    },
    created(){
        console.log('main - created')
        merge(this.pageStyle, this.schema.style)
        this.widgets = cloneDeep(this.schema.widgets)
        this.charts = cloneDeep(this.schema.charts)
        this.chartContainers = this.charts.map(c=>{
            let width = c.size[0]
            let height = c.size[1]
            let left = c.position[0]
            let top = c.position[1]
            if(typeof width === 'number'){
                width += 'px'
            }
            if(typeof height === 'number'){
                height += 'px'
            }
            if(typeof left === 'number'){
                left += 'px'
            }
            if(typeof top === 'number'){
                top += 'px'
            }
            return {
                id: c.id,
                style:{ 
                    // position:'absolute',
                    width,
                    height,
                    left,
                    top
                }
            }
        })
    },   
    render(){
        console.log('main - render')
        return (
            <div class="cv-wrapper" style={ this.pageStyle }>
                {
                    // 基础部件
                    this.widgets.map(c=>{
                         switch(c.type){
                            case 'input': return <cv-input props={ {cfg:c} }/>
                            case 'select': return <cv-select props={{cfg:c}} />
                            case 'date':
                            case 'datetime':
                                return <cv-datepicker props={{cfg:c}} />
                            case 'dynamicLabel': return <cv-dynamic-label  props={ {cfg:c} } />
                            case 'freeTable': return <cv-free-table props={{cfg:c}} />
                            default: return <span />
                        }
                    })                    
                }
                {
                    // 图表组件容器
                    this.chartContainers.map(c=>{
                       return <div class="cv-chart-wrapper" id={ chartHelper.prefixId+ c.id } style={ c.style }></div>
                    })
                }
            </div>
        )
    },
    beforeMount(){
        console.log('main - before mount')
    },
    mounted(){
        console.log(`main - mounted idpage: ${this.schema.id}`)
        this.$cvr.addComp(this.schema.id, this)
        this.renderCharts()
        this.$cvr.emit(this.schema.id + '_page_ready')
    },
    destroyed(){
        this.$cvr.removeComp(this.schema.id)
    }
}
</script>

<style lang="scss"  scoped>
.cv-wrapper{
    position: relative;    
    padding:10px;
    box-sizing: border-box;
    width:100%;
    height: 100%;
    overflow: auto;
    /deep/ table.cv-free-table-content{
        td{
            padding:2px 6px;
        }
    }
    .cv-widget, .cv-chart-wrapper{
        background: #ffffff;
        position: absolute;
        box-sizing: border-box;
    }
}
</style>