/*
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-21 13:06:34
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-21 13:25:43
 * @Tool: Auto Generated by koroFileHeader
 */
export default {
    content:`<div id="tinydemo" class="mce-content-body" style="position: relative;" spellcheck="false"><p style="line-height: 125%; margin-top: 0pt; margin-bottom: 0pt; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">1.2020</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">年</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">1-7</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">月，</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">风电公司\${0}\${1}</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">总损失电量</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">64763</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">万</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">kWh</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">。其中</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">新疆区域</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">27782</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">万</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">kWh</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">（</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">43%</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">），</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">甘肃区域</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">15625</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">万</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">kWh</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">（</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">24%</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">），</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">张北区域</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">10769</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">万</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">kWh</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">（</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">16%</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">），其他区域累计</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">10587</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">万</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">kWh</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">（</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">17%</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">）。</span></p><p style="line-height: 125%; margin-top: 0pt; margin-bottom: 0pt; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">2.</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">风电公司</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">总损失折算小时数</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">229</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">小时。</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">新疆区域</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">348</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">小时，</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">蒙西区域</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">349</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">小时，高于风电公司平均值，约</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">90%</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">损失小时数由限电损失造成；</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">西中区域</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">，</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">五峰风电</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">无限电损失，其中</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">五峰风电</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">156</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">小时，显著高于其他风场除限电因素外的其他损失。</span></p><p>
    
    
    
    <span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;
    mso-fareast-font-family:仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:
    minor-bidi;color:black;mso-color-index:1;mso-font-kerning:12.0pt;language:en-US;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">3.</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">风电公司</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">损失等效小时数同比</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:#00B050;
    mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:solid;
    mso-style-textfill-fill-color:#00B050;mso-style-textfill-fill-alpha:100.0%">下降</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:#00B050;
    mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:solid;
    mso-style-textfill-fill-color:#00B050;mso-style-textfill-fill-alpha:100.0%">12%</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">，其中</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">甘肃区域</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:#00B050;
    mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:solid;
    mso-style-textfill-fill-color:#00B050;mso-style-textfill-fill-alpha:100.0%">降低</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:#00B050;
    mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:solid;
    mso-style-textfill-fill-color:#00B050;mso-style-textfill-fill-alpha:100.0%">24.3%</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">，</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">蒙东区域</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:#00B050;
    mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:solid;
    mso-style-textfill-fill-color:#00B050;mso-style-textfill-fill-alpha:100.0%">降低</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:#00B050;
    mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:solid;
    mso-style-textfill-fill-color:#00B050;mso-style-textfill-fill-alpha:100.0%">67.5%</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">，</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">西中区域</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:#00B050;
    mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:solid;
    mso-style-textfill-fill-color:#00B050;mso-style-textfill-fill-alpha:100.0%">降低</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:#00B050;
    mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:solid;
    mso-style-textfill-fill-color:#00B050;mso-style-textfill-fill-alpha:100.0%">68%</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">；</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;font-weight:bold;
    mso-style-textfill-type:solid;mso-style-textfill-fill-themecolor:text1;
    mso-style-textfill-fill-color:black;mso-style-textfill-fill-alpha:100.0%">五峰风电</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">同比</span><span style="font-size:
    14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:仿宋;
    mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:red;
    mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:solid;
    mso-style-textfill-fill-color:red;mso-style-textfill-fill-alpha:100.0%">增加</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:red;
    mso-font-kerning:12.0pt;language:en-US;mso-style-textfill-type:solid;
    mso-style-textfill-fill-color:red;mso-style-textfill-fill-alpha:100.0%">954.6%</span><span style="font-size:14.0pt;font-family:仿宋;mso-ascii-font-family:仿宋;mso-fareast-font-family:
    仿宋;mso-bidi-font-family:+mn-cs;mso-bidi-theme-font:minor-bidi;color:black;
    mso-color-index:1;mso-font-kerning:12.0pt;language:zh-CN;mso-style-textfill-type:
    solid;mso-style-textfill-fill-themecolor:text1;mso-style-textfill-fill-color:
    black;mso-style-textfill-fill-alpha:100.0%">。</span><br></p></div>`
}