/*
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-12 15:31:28
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-20 09:08:18
 * @Tool: Auto Generated by koroFileHeader
 */
import fd_table_indicator_summary from './fd_table_indicator_summary'
const samplePage = {
    id:'01',
    title:'风场运维情况',
    subTitle:'',
    dataTransfer:{}, // 这个接收由页面跳转或组件钻取传入的数据
    style:{
        background:'#d7f6fa',
        width:'100%',
        height:'calc(100% - 60px)'
    },
    widgets:[{
        id:'01-010',
        idParent:'01',
        type:'button',
        text:'刷新',
        events:['click']
    },{
        id:'01-011',
        idParent:'01',
        type:'input',
        value:'orange',
        placeholder:'请输入',
        style:{
            width:'200px',
            height:'30px',
            top:'20px',
            left:'20px'
        },
        events:['change']
    },{
        id:'01-012',
        idParent:'01',
        type:'select',
        value:'1',
        style:{
            width:'120px',
            height:'20px',
            top:'20px',
            left:'260px'
        },
        placeholder:'请选择',
        dataSource:{
            id:'',
        },
        events:['change']
    },{
        id:'01-016',
        idParent:'01',
        type:'select',
        value:'',
        style:{
            width:'120px',
            height:'20px',
            top:'20px',
            left:'390px'
        },
        placeholder:'月份',
        dataSource:{
            data:[
             {value:'01',label:'1月'},
             {value:'02',label:'2月'},
             {value:'03',label:'3月'},
             {value:'04',label:'4月'},
             {value:'05',label:'5月'},
             {value:'06',label:'6月'},
             {value:'07',label:'7月'},
             {value:'08',label:'8月'},
             {value:'09',label:'9月'},
             {value:'10',label:'10月'},
             {value:'11',label:'11月'},
             {value:'12',label:'12月'},
            ]
        },
        events:['change']
    },{
        id:'01-013',
        idParent:'01',
        type:'date',
        style:{
            width:'140px',
            height:'20px',
            top:'20px',
            left:'520px'
        },
        value:'${dateNow}'
    },{
        id:'01-014',
        idParent:'01',
        type:'dynamicLabel',
        content:'风电运维情况，时间-${0},区域-${1},${0}',
        style:{
            fontSize:'16px',
            color:'#ff00ff',
            fontWeight:'600',
            left:'670px',
            top:'20px'
        },
        slots:[{
            from:'01-013',
            trigger:['change','init'],
            get:'value',
            style:{
                fontSize:'30px',
                color:'blue'
            }
        },{
            from:'01-012',
            trigger:['init','change'],
            get:'text',
            style:{
                color:'purple'
            }
        }]
    },{
        id:'01-015',
        idParent:'01',
        type:'freeTable',
        style:{
            background:'#f0f8ff',
            boxShadow: '2px 2px 6px 0 #ccc',
            top:'700px',
            left:'10px',
            width:'calc(100% - 20px)',
            minHeight:'800px',
            padding:' 10px 20px',
        },   
        dataSource:{
            id:'',
            lazyLoad: true            
        },
        listen:[{
            from:'01-012',
            trigger:['change'],
            action:[{ 
                method:'loadData',
                type:'data',
                params:[{
                    prop:'region',
                    valueFrom:'01-012'
                },{
                    prop:'year',
                    valueFrom:'01-013'
                }]
            },{ 
                method:'updateTitle',
                type:'data',
                params:[{
                    prop:'region',
                    valueFrom:'01-012',
                    get:'text'
                },{
                    prop:'year',
                    valueFrom:'01-013',
                    get:'value'
                }]
            }]
        },{
            from:'01-013',
            trigger:['change','init'],
            action:[{ 
                method:'updateTitle',
                type:'data',
                params:[{
                    prop:'region',
                    valueFrom:'01-012',
                    get:'text'
                },{
                    prop:'year',
                    valueFrom:'01-013'
                }]
            }]
        }],
        ...fd_table_indicator_summary
    }],    
    charts: [{
        id: '01-001',
        idParent:'01',
        type: 'line',
        position:[10, 100],
        size:[600, 600],
        dataSource:{
            id: 0,
            name: '',
            lazyLoad:true,
            filter:{
                selectFields: ['time','power'],
                where: '',
            },
            orderBy: ''
        },
        pipeline:{
            id: 0,
            name: ''
        },
        output:{
            x: 'time',
            y: 'power'
        }, 
        events:[{
            name:'click',
            interop:{
                drillDown:{
                    trigger:'item', // 点击图表的哪部分执行钻取
                    target:'self', // 'self':组件自身替换，'blank':打开一个只包含自身组件的新页,'popup': 弹窗形式显示自身组件, 'page':新的页面组件
                    dataTransfer:{}, // 通常作用于chart组件的dataSource.filter.where条件
                    idPage:'01' // 其他页面的ID，当target是page的时候，应用此属性，如果钻取页结构与当前页一致，可将id设置为当前页
                    },
                linkage:{ //同一页的不同组件联动
                        trigger:'item', // 点击图表的哪部分联动
                        dataTransfer:{},
                        idComponents:['002','003']
                }
            }
        }],    
        listen:[{
            from:'01-011',
            trigger:['change'],
            action:[{ 
                method:'loadData',
                type:'data',
                params:[{
                    prop:'time',
                    valueFrom:'01-011'
                },{
                    prop:'power',
                    valueFrom:'01-011'
                }]
            }]
        },{
            from:'01-001',
            trigger:['click'],
            action:[{ 
                method:'onEventTrigger',
                type:'chartStyle',
                params:[{
                    prop:{series:[{
                        itemStyle:{
                            color:'red'
                        }
                    }]}
                }]
            }]
        }]
    },{
        id:'01-002',
        idParent:'01',
        type:'bar',        
        position:[700, 100],
        size:[600, 600],
        dataSource:{
            id: 0,
            name: '',
            lazyLoad: true,
            filter:{
                selectFields: ['time','power'],
                where: '',
            },
            orderBy: '',
            params:{
                time:'2020-10-20',
                power:200
            }
        },
        chartOption:{
            series:[{
                itemStyle:{
                    color:'green'
                }
            }]
        },
        events:[{
            name:'click',
            interop:{
                drillDown:{
                    trigger:'item', // 点击图表的哪部分执行钻取
                    target:'self', // 'self':组件自身替换，'blank':打开一个只包含自身组件的新页,'popup': 弹窗形式显示自身组件, 'page':新的页面组件
                    dataTransfer:{}, // 通常作用于chart组件的dataSource.filter.where条件
                    idPage:'01' // 其他页面的ID，当target是page的时候，应用此属性，如果钻取页结构与当前页一致，可将id设置为当前页
                    },
                linkage:{ //同一页的不同组件联动
                        trigger:'item', // 点击图表的哪部分联动
                        dataTransfer:{},
                        idComponents:['002','003']
                }
            }
        }], 
        listen:[{
            from:'01-011',
            trigger:['change','init'],
            action:[{ 
                method:'loadData',
                type:'data',
                params:[{
                    prop:'time',
                    valueFrom:'01-011'
                },{
                    prop:'power',
                    valueFrom:'01-011'
                }]
            },{ 
                method:'draw',
                type:'chartStyle',
                params:[{
                    prop:{series:[{
                        itemStyle:{
                            color:'?s'
                        }
                    }]},
                    valueFrom:'01-011'
                }]
            }]
        },{
            from:'01-002',
            trigger:['click'],
            action:[{ 
                method:'onEventTrigger',
                type:'chartStyle',
                params:[{
                    prop:{series:[{
                        itemStyle:{
                            color:'red'
                        }
                    }]}
                }]
            }]
        }]
    }]
}
export default samplePage