<!--
 * @Description: 设计列表，各项点击后进入设计界面
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-12-01 11:21:28
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-12-05 14:52:49
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
  <div class="list-design-page">
      <div v-for="page in listPages" :key="page.id" class="item-design-page">
          <div class="title-wrapper">
            <h3 class="title" v-if="!page.editTitle">{{ page.title }}</h3>
            <el-input v-else v-model="page.title" type="textarea" :rows="7"/>
            <span class="hover-show el-icon-edit" v-if="!page.editTitle" @click="setPageStatusEdit(page,true)"></span>
            <span v-else class="title-save el-icon-check" @click="updateTitle(page)"/>
          </div>
          <div>ID:{{ page.id }}</div>
          <div>创建人:{{ page.creator }}</div>
          <div class="design-operation">
              <span @click="preview(page)">预览</span>
              <span @click="edit(page)">设计</span>
              <span @click="removePage(page.id)">删除</span>
          </div>
      </div>
      <div class="item-design-page plus-item" @click="addNewEmpty">
          <span>+</span>
      </div>
  </div>
</template>

<script>
import {uuid} from '../common'
import {updatePageTitle, getPageList, addNewPageCfg }  from '../api'
export default {
    name:'ListDesignPages',
    data(){
        return {
            listPages:[]
        }
    },
    methods:{
        updateTitle(page){
            this.setPageStatusEdit(page,false)
            //todo save serverside
            updatePageTitle(page)
        },
        setPageStatusEdit(page, editing){
            this.$set(page,'editTitle',editing)
        },
        getDesignedPages(){
            this.listPages = getPageList()
        },        
        removePage(idPage){
            this.$confirm('确定删除吗','提示').then(()=>{                
                let idx = this.listPages.findIndex(c=>c.id === idPage)
                if(idx>=0){
                    this.listPages.splice(idx,1)
                    //todo 后台删除
                     const designPages = window.localStorage.getItem('designPages')
                    let pages = []
                    if(designPages){
                        pages = JSON.parse(designPages)                               
                    }
                    idx = pages.findIndex(c=>c.id === idPage) 
                    if(idx>=0){
                        pages.splice(idx,1)
                        window.localStorage.setItem('designPages',JSON.stringify(pages))
                    }
                }
            })
        },
        preview(page){
            this.$emit('preview', {...page})
        },
        edit(page){
            this.$emit('edit', {...page})
        },
        addNewEmpty(){
            const newPageBriefInfo = {id:uuid(),title:'未命名',creator:'luanf'}
            this.listPages.push(newPageBriefInfo)
            const pageCfg = {
                id: newPageBriefInfo.id,
                title:newPageBriefInfo.title,
                creator: newPageBriefInfo.creator,
                style:{
                    backgroundColor:'#ffffff',
                    gridShow:false,
                    gridColor:'b3b3b3',
                    width:800,
                    height:800,
                    autoSize: true    
                },
                containers:[],
                shapes:[],
                widgets:[],
                charts:[]
            }
            addNewPageCfg(pageCfg)
        }
    },
    created(){
        this.getDesignedPages()
    }
}
</script>

<style lang="scss" scoped>
.list-design-page{
    display: flex;
    flex-flow: row wrap;
    justify-content: flex-start;
    align-items: center;
    align-content: flex-start;
    width: 100%;
    min-height: calc(100% - 60px);
    padding: 28px;
    box-sizing: border-box;
    background: #f4f4f4;
    .item-design-page{
        flex:0 0 auto;
        align-self: auto;
        box-sizing: border-box;
        position:relative;
        margin: 20px;
        height: 300px;
        width: 300px;
        padding: 20px;
        background: #ffffff;
        border-radius: 8px;
        transition: box-shadow .4s,transform .4s;
        color:#999999;
        font-size: 12px;
        .title-wrapper{
            padding: 20px 0;
            position: relative;
            height: 170px;
            color: #666666;
            .el-textarea /deep/ textarea{
                max-height: 160px;
            }
            .title{
                margin: 0;
                display: -webkit-box;
                -webkit-box-orient: vertical;
                -webkit-line-clamp: 7;
                font-size: 18px;
                font-weight: 500;
                word-break: break-all;
                overflow: hidden;
            }
            .title-save{
                cursor: pointer;
                position: absolute;
                right: 0;
                top: 0;
                font-size: 16px;
                &:hover{
                    color:#2b5bd6;
                }
            }
            .hover-show{
                display:none;
                cursor: pointer;
                position: absolute;
                left: 0;
                top: 0;
                font-size: 16px;
                &:hover{
                    color:#2b5bd6;
                }
            }
            &:hover{
                .hover-show{                    
                    display: inline-block;                    
                }
            }
        }
        &:hover{
            box-shadow: 0 8px 11px -5px rgba(0,0,0,.2),0 17px 26px 2px rgba(0,0,0,.14),0 6px 32px 5px rgba(0,0,0,.12);
            transform: translateY(-2%);
            .design-operation{
                visibility: 1;
                height: 80px;
                opacity: 1;
            }           
        }
        .design-operation{
            position: absolute;
            box-sizing: border-box;
            bottom:0;
            left:0;
            height: 0;
            padding: 10px;
            text-align: center;
            width: 100%;
            visibility: 0;
            opacity: 0;            
            background: #3d65c9;
            color:#ffffff;
            overflow: hidden;
            font-size: 16px;
            transition: height 0.4s ease-out, visibility 0.5s ease-in;
            span{
                cursor:pointer;
                margin:0 20px;
                line-height: 60px;
                display: inline-block;
                &:hover{
                    color:wheat;
                }
            }
        }
    }
    .plus-item{
        display: flex;
        justify-content: center;
        align-items: center;
        cursor:pointer;
        &:hover{
            color:#2b5bd6;
            border: 1px dashed #333333;
        }
        span{
            font-size: 80px;
            font-weight: 100;
            user-select: none;
        }
    }
}

</style>