<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-23 15:14:52
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-12-04 16:48:08
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
    <div ref="htmlFrag"
        :id="id"
        v-html="innerContent" 
        :class="innerClass"
        :style="innerStyle"
        draggable        
        @dragstart="onDragStart"
        @drag="_MouseMove"
        @dragend="onDragEnd"
        @mousedown="onClick" 
        @contextmenu="onContextMenu" 
        @dblclick="beginEdit" />
</template>

<script>
import { cloneDeep, debounce } from 'lodash'
export default {
    name:'DeHtmlFragment',
    props:{
        content:{
            type: String,
            default:''
        },
        id:{
            type: String,
            required:true
        },
        type:{
            type: String,
            default:'htmlFragment'
        },
        outStyle:{
            type:Object,
            required:true
        },
        isNewNode:{
            type:Boolean,
            default:false
        }
    },
    data(){
        return{
          active:false,
          settings:{
              style:null,
              content:''
          },
          innerStyle:null,
          innerContent:'',
          dragEvent:{
              x:0,
              y:0,
              left:0,
              top:0,
              isDragging:false
          }
        }
    },
    computed:{
        innerClass(){
            return {
                'de-html-fragment':true,
                active:this.active
            }
        }
    },
    created(){
        console.log(`widget ${this.id} created`)
        this.settings = {
            style: Object.assign({},this.outStyle),
            content: this.content
        }
        this.parseStyle()
        this.innerContent = this.settings.content
        this.$cvd.on(['clearSelect','selectNode'],this.onBlur)
        this.$cvd.on('changeWidget',this.updateSetting)
        this.$once('hook:beforeDestroy', ()=> {
            this.$cvd.off(['clearSelect','selectNode'],this.onBlur)
            this.$cvd.off('changeWidget',this.updateSetting)
        })
    },
    mounted(){
        // 新加入的节点触发一次点击
        if(this.isNewNode){
            //插入store
            this.$store.dispatch('designer/insertElement',{id:this.id,groupType:'widgets',type:this.type,...this.settings})
            this.onClick()
        }
    },
    methods:{
        onDragStart(e){
            const domEl = this.$refs.htmlFrag
            this.dragEvent.x = e.clientX;
            this.dragEvent.y = e.clientY;
            this.dragEvent.left = domEl.offsetLeft;
            this.dragEvent.top = domEl.offsetTop;
            this.dragEvent.isDragging = true;
            console.log('dragEvent start',this.dragEvent)
        },
        _MouseMove(e){
            if (!this.dragEvent.isDragging) {
                return;
            }
            e.dataTransfer.dropEffect = 'move'
            if(!this.dragEvent.isNotifyHideFrame){
                this.$cvd.emit('hideWidgetFrame')
                this.$emit('stopedit')
                this.dragEvent.isNotifyHideFrame = true
            }

            const nx = e.clientX;
            const ny = e.clientY;
            const nl = nx - (this.dragEvent.x - this.dragEvent.left);
            const nt = ny - (this.dragEvent.y - this.dragEvent.top);
            if(nl<0 || nt<0){
                return false
            }
            const domEl = this.$refs.htmlFrag
            domEl.style.left = nl + 'px';
            domEl.style.top = nt + 'px';
        },
        onDraging:debounce(function(e){
            this._MouseMove(e)
        },20),
        onDragEnd(e){
            // const domEl = this.$refs.htmlFrag
            this.dragEvent.isDragging = false
            this.dragEvent.isNotifyHideFrame = false
            const nx = e.clientX;
            const ny = e.clientY;
            const nl = nx - (this.dragEvent.x - this.dragEvent.left);
            const nt = ny - (this.dragEvent.y - this.dragEvent.top);
            this.settings.style.left = nl
            this.settings.style.top = nt
            this.$cvd.emit('resizeWidget',{id:this.id,box:this.getBoundingRect()})
        },
        onClick(){
            this.active = true
            this.$cvd.emit('selectWidget', { id:this.id, node: this, type:'htmlFragment' })
        },
        getSettings(){
            return {id:this.id,settings:cloneDeep(this.settings)}
        },
        onBlur(e){
            if(e && e.id && e.id === this.id){
                return
            }
            this.active = false
        },
        updateSetting(prop){
            if(prop.id!==this.id){
                return
            }
            if('style' in prop){
                let newStyle = {...prop.style}
                Object.assign(this.settings.style, newStyle)
                this.parseStyle()
                this.$emit('updateEditorBackground',{id:this.id,backgroundColor:this.settings.style.backgroundColor})
            }
            if('content' in prop){
                this.innerContent = this.settings.content = prop.content
            }
            // 更新store
            this.$store.dispatch('designer/updateElement', {id:this.id,groupType:'widgets',type:this.type,...this.settings})
        },
        parseStyle(){
            let st = this.settings.style

            let temStyle = {
                top:`${st.top}px`,
                left:`${st.left}px`,
                width:typeof st.width === 'string'? st.width : `${st.width}px`,
                height:typeof st.height === 'string'? st.height : `${st.height}px`,
                border:`${st.borderSize}px ${st.borderType} ${st.borderColor}`,
                borderRadius:`${st.borderRadius}px`,
                paddingLeft:`${st.paddingLeft}px`,
                paddingRight:`${st.paddingRight}px`,
                paddingTop:`${st.paddingTop}px`,
                paddingBottom:`${st.paddingBottom}px`,
                boxShadow:`${st.shadowPosition[0]}px ${st.shadowPosition[1]}px ${st.shadowBlur}px ${st.shadowSpread}px ${st.shadowColor} ${st.shadowInset}`,
                backgroundColor: st.backgroundColor
            }
            this.innerStyle = temStyle
        },
        onContextMenu(e){
            e.preventDefault()
        },
        beginEdit(){
            this.$emit('edit',{id:this.id,content:this.innerContent,backgroundColor:this.innerStyle.backgroundColor})
        },
        getBoundingRect(){
            let st = this.settings.style
            return {
                x: st.left,
                y: st.top,
                width: st.width,
                height: st.height
            }
        }
    }
}
</script>

<style lang="scss" scoped>
.de-html-fragment{
    position: absolute;
    box-sizing:border-box;
    user-select: none;
    &.active{
        border:1px solid red;
    }
}
</style>