<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-23 15:14:52
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-23 17:30:56
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
  <div class="de-html-view" v-html="innerContent" />
</template>

<script>
export default {
    name:'DeHtmlView',
    props:{
        content:{
            type: String,
            default:''
        }
    },
    data(){
        return{
            innerStyle:{}
        }
    },
    computed:{
        innerContent(){
            return this.content
        }
    }
}
</script>

<style lang="scss" scoped>
.de-html-view{
    position: absolute;
    margin: 0 auto;
    top:100px;
}
</style>