/*
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-23 16:42:52
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-23 16:50:51
 * @Tool: Auto Generated by koroFileHeader
 */

function* next_id(){
    let current_id = 0
    while(true){
        current_id++
        yield current_id
    }
}
let g = next_id()

class DeDomWidget{
    constructor(cfg){
        this.id = g.next().value
        this.cfg = cfg
    }
}
export default DeDomWidget