/*
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-23 16:42:52
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-26 10:40:57
 * @Tool: Auto Generated by koroFileHeader
 */
class DeDomWidget{
    constructor(cfg,editor){
        // this.id = g.next().value
        this.editor = editor
        this.id = editor.uuid()
        this.type = cfg.type
        this.shape = {...cfg.shape}
    }
    getDefaultCfg(){
        switch(this.type){
            case 'htmlFragment':
                return  {
                    id:this.id, 
                    type:this.type,
                    content:'', 
                    style:{
                        top:this.shape.y,
                        left:this.shape.x,
                        width:200,
                        height:60,
                        borderSize:1,
                        borderType:'solid',
                        borderColor:'#cccccc',
                        borderRadius:0,
                        paddingLeft:0,
                        paddingRight:0,
                        paddingTop:0,
                        paddingBottom:0,
                        shadowPosition:[0,0],    
                        shadowSpread:0,
                        shadowBlur:4,
                        shadowColor:'#eeeeee',
                        shadowInset:'', // inset
                        backgroundColor:'#ffffff'
                    }
                }
            default:
                break
        }        
    }
}
export default DeDomWidget