<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-21 16:57:55
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-12-14 16:07:24
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
    <div class="de-property-switcher property-canvas">
        <header>画布</header>
        <el-tabs value="property" type="border-card">
            <el-tab-pane label="属性" name="property">
                <el-collapse v-model="expandItems">
                    <el-collapse-item title="尺寸" name="size">
                        <number-input :disabled="autoSize" v-model="canvas.width" prefix="宽" suffix="px ;" width="80px" inputWidth="40px" :min="100" />
                        <number-input :disabled="autoSize" v-model="canvas.height" prefix="高" suffix="px" width="80px" inputWidth="40px" :min="100" />
                        <el-checkbox style="width:20px;" size="mini" v-model="autoSize">自动</el-checkbox>
                    </el-collapse-item>
                    <el-collapse-item class="content-full" title="背景" name="color">
                        <color-indicator type="sketch" v-model="background.color" pickerShow label="填充" @input="updateBackgroundFill" />
                    </el-collapse-item>
                    <el-collapse-item class="content-full" title="网格线" name="grid">                       
                        <el-checkbox style="margin-left:20px;" size="small" v-model="grid.show" @change="toggleShowGrid">网格线</el-checkbox>
                        <color-indicator type="compact" v-model="grid.color" label="颜色" pickerShow @input="updateGridColor" />
                    </el-collapse-item>
                </el-collapse>
            </el-tab-pane>
            <el-tab-pane label="动作" name="action">动作</el-tab-pane>
        </el-tabs>        
    </div>
</template>
<script>
import ColorIndicator from '../components/colorIndicator'
import NumberInput from '../components/numberinput'
export default {
    name:'PropCanvas',
    components:{
        ColorIndicator,
        NumberInput
    },
    props:{
      cfg:{
          type:Object,
          required:true
      }
    },
    data(){     
        return {
            expandItems:['size','color','grid'],
            canvas:{
                width:0,
                height:0
            },
            autoSize:true,
            background:{
                color:'#ffffff',
            },
            grid:{
                color:'#b3b3b3',
                show:false
            },
            propReady: false
        }
    },
    watch:{
        '$props.cfg':{
            handler(newer){
                this.initStyle(newer)
            }
        },
        // canvas:{
        //     handler(newer){ 
        //         this.$cvd.emit('setCanvasSize',{width:newer.width,height:newer.height})
        //     },
        //     deep:true
        // }
        /*****
        ,
        '$data':{
            handler(newer){
                 // 保存store
                this.$store.dispatch('designer/updatePageStyle',{
                    backgroundColor:newer.background.color, 
                    width:newer.canvas.width,
                    height:newer.canvas.height,
                    gridShow:newer.grid.show,
                    gridColor:newer.grid.color,
                    autoSize: newer.autoSize
                })
            },
            deep:true
        }
        */
    },
    created(){
        // this.$cvd.on('canvasReady',this.setCanvasSize)
        // this.$once('hook:beforeDestroy', ()=> {
        //     this.$cvd.off('canvasReady',this.setCanvasSize)
        // })
    },
    updated(){
        console.log('this.propReady in updated', this.propReady)
        if(!this.propReady){
            return
        }
        let newPageCfg = {
            backgroundColor: this.background.color, 
            width: this.canvas.width,
            height: this.canvas.height,
            gridShow: this.grid.show,
            gridColor: this.grid.color,
            autoSize: this.autoSize
        }
        this.$store.dispatch('designer/updatePageStyle',newPageCfg)
        this.$cvd.emit('updatePageStyle',newPageCfg)
        console.log('canvas updated', newPageCfg)
    },
    mounted(){
        this.initStyle(this.$props.cfg)
    },
     methods:{
        initStyle(cfg){
            console.log('this.propReady', this.propReady)
            this.canvas = {
                width: cfg.width,
                height: cfg.height
            }
            this.background = {
                color:cfg.backgroundColor
            }
            this.grid = {
                color: cfg.gridColor,
                show: cfg.gridShow
            }
            this.autoSize = cfg.autoSize
            this.$nextTick(()=>{
                this.propReady = true
                console.log('this.propReady next tick', this.propReady)
            })
        },
        updateBackgroundFill(){
            // this.$cvd.emit('updateBackgroundStyle',{style:{fill: color }})
            // // 保存store
            // this.$store.dispatch('designer/updatePageStyle',{backgroundColor:color})
        },
        updateGridColor(){
            // this.$cvd.emit('updateGridColor', color)
        },
        toggleShowGrid(){
            // this.$cvd.emit('toggleShowGrid', this.grid.show)
        },
        // setCanvasSize(size){
        //     this.canvas = {...size}
        // }
  }
}
</script>