<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-21 16:57:55
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-23 16:06:09
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
    <div class="de-property-switcher property-canvas">
        <header>画布</header>
        <el-tabs value="property" type="border-card">
            <el-tab-pane label="属性" name="property">
                <el-collapse v-model="expandItems">
                    <el-collapse-item title="尺寸" name="size">
                        <number-input v-model="canvas.width" prefix="宽" suffix="px ;" width="100px" :min="100" />
                        <number-input v-model="canvas.height" prefix="高" suffix="px" width="100px" :min="100" />
                    </el-collapse-item>
                    <el-collapse-item class="content-full" title="背景" name="color">
                        <color-indicator type="sketch" v-model="background.color" pickerShow label="填充" @input="updateBackgroundFill" />
                    </el-collapse-item>
                    <el-collapse-item class="content-full" title="网格线" name="grid">                       
                        <el-checkbox style="margin-left:20px;" size="small" v-model="grid.show" @change="toggleShowGrid">网格线</el-checkbox>
                        <color-indicator type="compact" v-model="grid.color" label="颜色" pickerShow @input="updateGridColor" />
                    </el-collapse-item>
                </el-collapse>
            </el-tab-pane>
            <el-tab-pane label="动作" name="action">动作</el-tab-pane>
        </el-tabs>        
    </div>
</template>
<script>
import ColorIndicator from '../components/colorIndicator'
import NumberInput from '../components/numberinput'
export default {
    name:'PropCanvas',
    components:{
        ColorIndicator,
        NumberInput
    },
    data(){     
        return {
            expandItems:['size','color','grid'],
            canvas:{
                width:800,
                height:800
            },
            background:{
                color:'#ffffff',
            },
            grid:{
                color:'#b3b3b3',
                show:false
            }
        }
    },
    watch:{
        canvas:{
            handler(newer){
                this.$cvd.emit('setCanvasSize',{width:newer.width,height:newer.height})
            },
            deep:true
        }
    },
    created(){
        this.$cvd.on('canvasReady',this.setCanvasSize)
        this.$once('hook:beforeDestroy', ()=> {
            this.$cvd.off('canvasReady',this.setCanvasSize)
        })
    },
     methods:{
        updateBackgroundFill(color){
            this.$cvd.emit('updateBackgroundStyle',{style:{fill: color }})
        },
        updateGridColor(color){
            this.$cvd.emit('updateGridColor', color)
        },
        toggleShowGrid(){
            this.$cvd.emit('toggleShowGrid', this.grid.show)            
        },
        setCanvasSize(size){
            this.canvas = {...size}
        }
  }
}
</script>