<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-21 16:57:55
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-12-14 15:34:20
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
   <div class="de-property-switcher property-html-fragment">
          <header>
            HTML富文本
          </header>
          <el-tabs value="property" type="border-card">
            <el-tab-pane label="属性" name="property">
                <el-collapse v-model="expandItems">
                    <el-collapse-item title="尺寸" name="size">
                        <number-input v-model="style.width" prefix="宽" suffix="px ;" width="100px" :min="0" />
                        <number-input v-model="style.height" prefix="高" suffix="px" width="100px" :min="0" />
                    </el-collapse-item>
                  <el-collapse-item title="边框" name="border">
                        <number-input v-model="style.borderSize" prefix="宽" suffix="px ;" width="100px" :min="0" />
                    </el-collapse-item>
                    <el-collapse-item title="内边距" name="padding">
                       <div>
                           <number-input v-model="style.paddingLeft" prefix="左" suffix="px ;" width="100px" :min="0" />
                           <number-input v-model="style.paddingRight" prefix="右" suffix="px" width="100px" :min="0" />
                       </div>
                        <div>
                           <number-input v-model="style.paddingTop" prefix="上" suffix="px ;" width="100px" :min="0" />
                           <number-input v-model="style.paddingBottom" prefix="下" suffix="px" width="100px" :min="0" />   
                        </div>
                    </el-collapse-item>
                    <el-collapse-item class="content-full" title="投影" name="shadow">
                        <color-indicator type="compact" v-model="style.shadowColor" label="颜色" />
                    </el-collapse-item>
                    <el-collapse-item class="content-full" title="背景色" name="background">
                        <color-indicator type="sketch" v-model="style.backgroundColor" pickerShow label="填充" />
                    </el-collapse-item>
                    <el-collapse-item title="插值变量" name="content">
                    </el-collapse-item>
                </el-collapse>
            </el-tab-pane>
            <el-tab-pane label="动作" name="action">动作</el-tab-pane>
        </el-tabs>
      </div>
</template>
<script>

import ColorIndicator from '../components/colorIndicator'
import NumberInput from '../components/numberinput'
import { cloneDeep } from 'lodash'

export default {
  name: 'PropHtmlFragment',
   components:{
      ColorIndicator,
      NumberInput
   },
   props:{
       cfg:{
           type:Object,
           default:null
       }
   },
  data(){
     return{
        id:null,
        expandItems:['size','border','padding','shadow','background','content'],
        style:{
            top:0,
            left:0,
            width:200,
            height:60,
            borderSize:1,
            borderType:'solid',
            borderColor:'#cccccc',
            borderRadius:0,
            paddingLeft:0,
            paddingRight:0,
            paddingTop:0,
            paddingBottom:0,
            shadowPosition:[0,0],    
            shadowSpread:0,
            shadowBlur:4,
            shadowColor:'#eeeeee',
            shadowInset:'',
            backgroundColor:'#ffffff'
        },
        content:''
     }
  },
  watch:{
      style:{
          handler(newer){
              console.log('changeWidget',newer)
              this.$cvd.emit('changeWidget',{id:this.id, style:{...newer}})
          },
          deep: true
      },
      '$props.cfg':{
          handler(newer){
              this.initConfig(newer)
          },
          deep: true,
          immediate:true
      }
  },
  created(){
      this.initConfig(this.cfg)
      this.$cvd.on('resizeWidget',this.onResize)
      this.$once('hook:beforeDestroy',()=>{
          this.$cvd.off('resizeWidget', this.onResize)
      })
  },
  mounted(){
      
  },
  methods:{
     onResize(param){
         console.log('onResize',param,param.id,this.id)
        if(param.id !== this.id){
            return
        }
        
        if(param.box){
            let newStyle = {
                top:param.box.y,
                left:param.box.x,
                width:param.box.width,
                height:param.box.height
            }
            this.style = Object.assign(this.style,newStyle)
        }
     },
     initConfig(cfg){
        if(!cfg) return
        this.id = cfg.id
        this.style = cloneDeep(cfg.settings.style)
        this.content = cfg.settings.content
     },
     
  }
}
</script>
