<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-21 16:57:55
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-22 10:21:56
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
   <div class="de-property-switcher property-html-fragment">
          <header>
            HTML富文本
          </header>
          <section>
             property
             <sketch-picker v-model="setting.fill" @input="updateFill" />
          </section>
      </div>
</template>
<script>

import { Sketch } from 'vue-color'
export default {
  name: 'PropHtmlFragment',
  components:{
   'sketch-picker': Sketch
  },
  data(){
     return{
        setting:{
           fill:''
        }
     }
  },
  mounted(){
    
  },
  methods:{
     updateFill(color){
        this.setting.fill = color.hex
     }
  }
}
</script>
