/*
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-16 10:08:07
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-18 11:58:38
 * @Tool: Auto Generated by koroFileHeader
 */

 export function loadTableData(ds){
    if(ds){
        return {
            pjfs: 20,
            lyxsswdl: 123,
            lyxsfdl: 45,
            gztj: 4,
            sytj:2,
            nlklyl:78,
            gzpc:40,
            pjgzsc:60,
            pjwgzsj:240,
            jzxqx:`发电机、变频器、变桨、齿轮箱、安全链故障是发生频次较高且停机时间长的故障类型。其中，变桨电机损坏、桨叶温控线损坏、发电机损坏、发电机碳刷磨损，是场内机组普遍存在的集中性缺陷。
            另外，发电机6月份偏航故障显著增加，1002 安全链故障4-6月不断增多。
            `,
            wxpc:40
        }
    }
}

export function loadKeyValueArrayData(ds){
    if(ds){
        return [{
            value:'1',label:'张北区域'
        },{
            value:'2',label:'新疆区域'
        },{
            value:'3',label:'甘肃区域'
        },{
            value:'4',label:'蒙西区域'
        }]
    }
}

export function loadLineBarData(ds){
    if(ds){
        return {
            xAxisData: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            seriesData:[820, 932, 901, 934, 1290, 1330, 1320],
        }
    }
}
