/*
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-16 16:57:26
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-17 09:55:17
 * @Tool: Auto Generated by koroFileHeader
 */
const barSchema = {
    tooltip:{
        trigger:'axis'
    },
    xAxis:{
        type: 'category',
        data:[]
    },
    yAxis:{
        type:'value'
    },
    series:[{
        data:[],
        markLine:{
            symbol:'none',
            lineStyle:{
                color:'#c60928',
                type:'solid',
                width:1,
                shadowColor: 'rgba(0, 0, 0, 0.5)',
                shadowBlur: 4,
                shadowOffsetY:2
            },
            data:[{ yAxis:600, xAxis:'Tue'},{type:'max'}]
        },
        type:'bar'
    }]
}

export default barSchema