<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-21 15:36:54
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-12-04 17:36:24
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
  <div class="design-property">
    <prop-canvas v-show="propType === 'canvas'" :cfg="canvasStyle" />
    <prop-html-fragment v-show="propType === 'htmlFragment'" :cfg="htmlFragmentCfg" />
  </div>
</template>
<script>
import PropCanvas from './switcher/canvas'
import PropHtmlFragment from './switcher/htmlFragment'

export default {
  name: 'DesignerProperty',
  components:{
    PropCanvas,
    PropHtmlFragment
  },
  props:{
      cfg:{
          type:Object,
          required:true
      }
  },
  data(){
     return{
        propType:'canvas', // canvas,htmlFragment
        selElement:null,
        htmlFragmentCfg:null,
        canvasStyle:null
     }
  },
  watch:{
    '$props.cfg':{
        handler(newer){
            this.canvasStyle = {...newer}
        }
    }
  },
  created(){
    this.$cvd.on(['clearSelect','selectNode'],this.setPropPanel)
    this.$once('hook:beforeDestroy', ()=> {
      this.$cvd.off(['clearSelect','selectNode'],this.setPropPanel)
    })
  },
  mounted(){
    this.canvasStyle = {...this.$props.cfg}
  },
  methods:{
    setPropPanel(selElement){
      console.log('selElement Type',selElement)
      this.selElement = selElement
      // this.getSelElementProps(selElement)
      if(!selElement){
        this.propType = 'canvas'
      }else if(selElement.type === 'htmlFragment'){
        this.propType ='htmlFragment'
        this.htmlFragmentCfg = selElement.node.getSettings() // {id:,settings}
      }
    }
  }
}
</script>

<style lang="scss" scoped>
.design-property{
     box-sizing: border-box;
    width: 260px;
    height:100%;
    border-left:1px solid #e6e9ed;
    background:#f4f4f4;
    font-size:14px;
    line-height: 26px;
    user-select: none;
    -webkit-user-select: none;
    /deep/ *{
      box-sizing: border-box;
    }
    .de-property-switcher{
      height: 100%;
      overflow:hidden;
      /deep/ header{
        height:30px;        
        line-height: 30px;
        font-size: 14px;
        font-weight: bold;
        text-indent: 1em;
        border-bottom:1px solid #e6e9ed;
        background: #454545;
        color:#ffffff;
      }
      /deep/ .el-tabs{
        height: calc(100% - 30px);
        overflow-y: auto;
        .el-tabs__content{
          padding:0;
          .el-collapse-item__header{
            height: 30px;
            line-height: 30px;
            background: #eeeeee;
            padding-left: 6px;
          }
          .el-collapse-item__content{
            padding:8px 16px;
            font-size: 12px;
          }
          .el-collapse-item.content-full .el-collapse-item__content{
            padding:8px 0;
          }
        }
        
      }
    }    
}

</style>
