<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-21 15:36:54
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-23 16:03:40
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
  <div class="design-property">
    <prop-canvas v-show="propType === 'canvas'" />
    <prop-html-fragment v-show="propType === 'htmlFragment'" />
  </div>
</template>
<script>
import PropCanvas from './switcher/canvas'
import PropHtmlFragment from './switcher/htmlFragment'

export default {
  name: 'DesignerProperty',
  components:{
    PropCanvas,
    PropHtmlFragment
  },
  data(){
     return{
        propType:'canvas', // canvas,htmlFragment
        selElement:null
     }
  },
  created(){
    this.$cvd.on('clearSelect',this.setPropType)
    this.$cvd.on('selectNode',this.setPropType)
    this.$cvd.on('selectHtmlView',this.setPropType)
     this.$once('hook:beforeDestroy', ()=> {
        this.$cvd.off('clearSelect',this.setPropType)
        this.$cvd.off('selectNode',this.setPropType)
      })
  },
  methods:{
    setPropType(selElement){
      console.log('selElement Type',selElement)
      this.selElement = selElement
      if(!selElement){
        this.propType = 'canvas'
      }else if(selElement.type === 'htmlView'){
        this.propType ='htmlFragment'
      }
    }
  }
}
</script>

<style lang="scss" scoped>
.design-property{
     box-sizing: border-box;
    width: 260px;
    height:100%;
    border-left:1px solid #e6e9ed;
    background:#f4f4f4;
    font-size:14px;
    line-height: 26px;
    user-select: none;
    -webkit-user-select: none;
    /deep/ *{
      box-sizing: border-box;
    }
    .de-property-switcher{
      height: 100%;
      overflow:hidden;
      /deep/ header{
        height:30px;        
        line-height: 30px;
        font-size: 14px;
        font-weight: bold;
        text-indent: 1em;
        border-bottom:1px solid #e6e9ed;
        background: #454545;
        color:#ffffff;
      }
      /deep/ .el-tabs{
        height: calc(100% - 30px);
        overflow-y: auto;
        .el-tabs__content{
          padding:0;
          .el-collapse-item__header{
            height: 30px;
            line-height: 30px;
            background: #eeeeee;
            padding-left: 6px;
          }
          .el-collapse-item__content{
            padding:8px 16px;
            font-size: 12px;
          }
          .el-collapse-item.content-full .el-collapse-item__content{
            padding:8px 0;
          }
        }
        
      }
    }    
}

</style>
