<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-22 18:39:44
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-23 13:49:58
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
  <div class="de-color-indicator" >
    <div><span class="indicator-label">{{ label }}</span><div class="indicator" :style="indicatorStyle" @click="showPicker=!showPicker"></div></div>
    <component v-show="showPicker" :is="type" v-model="pickedColor" @input="updateFill" />
  </div>
</template>

<script>
import { Sketch,Compact } from 'vue-color'
export default {
    name:'ColorIndicator',
    components:{
        'sketch': Sketch,
        'compact': Compact
    },
     props:{
        value:{
            type:String,
            default:'#ffffff'
        },
        label:{
            type:String,
            default:''
        },
        type:{
            type: String,
            default:'sketch'
        },
        pickerShow:{
            type: Boolean,
            default:false
        }
    },
    data(){
        return {
            pickedColor: null,
            showPicker: false            
        }
    },
    computed:{
        indicatorStyle(){
            return {
                backgroundColor:typeof this.pickedColor === 'string'? this.pickedColor : this.pickedColor.hex
            }
        }
    },
    created(){
        this.pickedColor =  this.$props.value
        this.showPicker = this.$props.pickerShow
    },
    methods:{
        updateFill(color){
            this.$emit('input', color.hex)
        }
    }
}
</script>

<style lang="scss" scoped>
.de-color-indicator{
    width:100%;
    position: relative;
    .indicator-label{
        margin-left:8px;
    }
    .indicator{
        width: 16px;
        height: 16px;
        border:1px solid black;
        position: absolute;
        background: #ffffff;
        right: 4px;
        top: 2px;
    }
    .vc-sketch,.vc-compact{
        width:100%;
    }
}

</style>