<!--
 * @Description:数值输入组件，可以加前缀后缀
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2020-11-22 18:39:44
 * @LastEditors: Luan Feng
 * @LastEditTime: 2020-11-23 14:30:21
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
    <div class="number-input-decorated" :style="{width,height}">
        <span v-if="prefix" class="number-input-prefix">{{ prefix }}</span>
        <el-input-number v-model="inputValue" :controls="controls" :size="size" :style="{width:inputWidth}" :min="min"/>
        <span v-if="suffix" class="number-input-suffix">{{ suffix }}</span>
    </div>
</template>

<script>
export default {
    name:'NumberInput',
     props:{
        controls:{
            type:Boolean,
            default:false
        },
        size:{
            type:String,
            default:'mini'
        },
        min:{
            type: Number,
            default:0
        },
        width:{
            type:String,
            default:'100%'
        },
        inputWidth:{
            type:String,
            default:'50px'
        },
        height:{
            type:String,
            default:'28px'
        },
        value:{
            type: [Number,String],
            default:''
        },
        suffix:{
            type: String,
            default: 'px'
        },
        prefix:{
            type: String,
            default: ''
        }
    },
    data(){
        return {
            // inputValue:''
        }
    },
    computed: {
        inputValue:{
            get(){
                return this.$props.value
            },
            set(v){
                this.$emit('input',v)
            }
        }
    }
}
</script>
<style lang="scss" scoped>
.number-input-decorated{
    display: inline-flex;
    line-height: 28px;
    .number-input-suffix{
        width:20px;
        margin-right: 4px;
    }
    .number-input-prefix{
        flex:1;
        text-align: right;
    }
    .el-input-number{
        margin:0 4px;
        /deep/ .el-input__inner{
            padding-left:2px;
            padding-right:2px;
            height: 20px;
            line-height: 20px;
            border-radius: 0;
            font-size: 12PX;
        }
    }
}
</style>